app/models.py
from . import db
from flask import current_app
from datetime import datetime
from .qpf import *
import os

class Forecast(db.Model):
    __tablename__ = 'forecasts'
    id = db.Column(db.Integer, primary_key=True)
    product = db.Column(db.String(16))
    period = db.Column(db.String(8))
    duration = db.Column(db.Integer)
    start_hour = db.Column(db.Integer)
    valid_start = db.Column(db.DateTime())
    valid_end = db.Column(db.DateTime())
    value = db.Column(db.Float)
    location_id = db.Column(db.Integer, db.ForeignKey('locations.id'))
    timestamp = db.Column(db.DateTime(), index=True, default=datetime.utcnow)
    latest = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return '<Forecast %s, %d, %d, %s>' % (self.period, self.duration, self.start_hour, str(self.timestamp))

class Location(db.Model):
    __tablename__ = 'locations'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    forecasts = db.relationship('Forecast', backref='location', lazy='dynamic')

    @property
    def latest_forecasts(self):
        return self.forecasts.filter_by(latest=True).all()

    def get_all_forecasts(self):
        for period, duration, start in QPF_FILES:
            print 'Fetching QPF: %s, %s, %s' % (period, duration, start)
            self.get_forecast(period, duration, start)

    def get_forecast(self, period, duration, start):
        tar_folder = current_app.config['QPF_TAR_FOLDER']
        shp_folder = current_app.config['QPF_SHP_FOLDER']
        folder, filename = fetch_and_extract(period, duration, start, tar_folder=tar_folder, shp_folder=shp_folder)
        qpf = qpf_from_shapefile(os.path.join(folder, filename), self.latitude, self.longitude)
        if qpf is None:
            return None
        print qpf
        valid_times = parse_valid_time(qpf['VALID_TIME'])
        old_forecasts = self.forecasts.filter_by(period=period, duration=duration, start_hour=start, latest=True).all()
        for old_forecast in old_forecasts:
            old_forecast.latest = False
            db.session.add(old_forecast)
        new_forecast = Forecast(
            product=qpf['PRODUCT'],
            period=period,
            duration=duration,
            start_hour=start,
            valid_start=valid_times[0],
            valid_end=valid_times[1],
            value=qpf['QPF'],
            location_id=self.id,
            latest=True)
        db.session.add(new_forecast)
        db.session.commit()

    def archive_forecasts(self):
        for forecast in self.forecasts.filter_by(period=period, duration=duration, start_hour=start, latest=True).all():
            forecast.latest=False
            db.session.add(forecast)
        db.session.commit()

    def last_update(self):
        forecasts = self.latest_forecasts
        last_update = min([f.timestamp for f in forecasts])
        return last_update

    def is_outdated(self, hours=6):
        dt = datetime.utcnow()-self.last_update()
        hours_since_update = dt.days*24 + dt.seconds/60.
        return hours_since_update > hours

    def __repr__(self):
        return '<Location %s>' % self.name

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.admin import Admin
from flask.ext.moment import Moment
from config import config
import os

bootstrap = Bootstrap()
db = SQLAlchemy()
moment = Moment()
admin = Admin(name='QPF Admin')

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    bootstrap.init_app(app)
    db.init_app(app)
    moment.init_app(app)
    admin.init_app(app)

    if not os.path.exists(app.config['QPF_TAR_FOLDER']):
        os.makedirs(app.config['QPF_TAR_FOLDER'])

    if not os.path.exists(app.config['QPF_SHP_FOLDER']):
        os.makedirs(app.config['QPF_SHP_FOLDER'])

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, flash, redirect, url_for
from flask.ext.admin.contrib.sqla import ModelView
from . import main
from .. import admin, db
from ..models import Forecast, Location
from datetime import datetime

AMOUNTS = {
    0: '0.0',
    0.01: '0.01-0.10',
    0.1: '0.10-0.25',
    0.25: '0.25-0.50',
    0.5: '0.50-0.75',
    0.75: '0.75-1.00',
    1: '1.00-1.25',
    1.25: '1.25-1.50',
    1.75: '1.75-2.00',
    2: '2.00-2.50',
    2.5: '2.50-3.00',
    3: '3.00-4.00',
    4: '4.00-5.00',
    5: '5.00-7.00',
    7: '7.00-10.00',
    10: '10.00-15.00',
    15: '15.00-20.00'
}

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/locations')
def locations():
    locations = Location.query.all()
    return render_template('location_list.html', locations=locations)

@main.route('/locations/<int:id>')
def location(id):
    location = Location.query.get_or_404(id)
    return render_template('location_detail.html',
        location=location, now=datetime.utcnow(),
        AMOUNTS=AMOUNTS)

@main.route('/locations/<int:id>/update')
def update_location(id):
    location = Location.query.get_or_404(id)
    if not location.is_outdated(hours=6):
        flash('Last update was performed less than 6 hours ago, wait a while')
        return redirect(url_for('main.location', id=id))
    try:
        location.get_all_forecasts()
    except Exception as e:
        flash('Error occured on server: %s' % (str(e)))
        return redirect(url_for('main.location', id=id))
    flash('Forecast successfully updated.')
    return redirect(url_for('main.location', id=id))

admin.add_view(ModelView(Location, db.session))
admin.add_view(ModelView(Forecast, db.session))

app/qpf/__init__.py
from fetch import fetch_and_extract, QPF_FILES
from qpf import qpf_from_shapefile, parse_valid_time

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}SEA{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<head>
    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}
</head>
{% endblock %}


{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
             data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">SEA</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.locations') }}">Locations</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block page_content %}
    {% endblock %}
    <hr>
    {% block footer %}
    <div class="footer">
        <p>&copy; 2014, <a href="http://walkerjeff.com">Jeffrey D. Walker</a></p>
    </div>
    {% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
<div class="jumbotron" style="background-image: url({{ url_for('static', filename='img/rain-84648_1280_fade.jpg') }}); background-size: 100%;">
<h1>Stormwater Event Assistant</h1>
<p>This application was created to assist in stormwater event sampling. It provides one-stop access to weather forecasts from multiple websites and for individual locations.</p>
<a href="{{ url_for('main.locations') }}" class="btn btn-primary"><b>Locations</b> <span class="glyphicon glyphicon-chevron-right"></span></a>
</div>
{% endblock %}

app/templates/location_detail.html
{% extends "base.html" %}
{% set link_nws = "http://forecast.weather.gov/MapClick.php?FcstType=graphical&lat=%f&lon=%f" % (location.latitude,location.longitude) %}
{% set link_radar = "http://radar.weather.gov/Conus/northeast.php" %}
{% set link_forecastio_embed = "http://forecast.io/embed/#lat=%f&lon=%f" % (location.latitude,location.longitude) %}
{% set link_forecastio_lines = "http://forecast.io/lines/#/f/lat=%f&lon=%f" % (location.latitude,location.longitude) %}
{% set link_forecastio = "http://forecast.io/#/f/%f,%f" % (location.latitude,location.longitude) %}
{% set link_wunderground = "http://www.wunderground.com/cgi-bin/findweather/getForecast?query=%f,%f" % (location.latitude,location.longitude) %}

{% block page_content %}
<h1>{{ location.name }}</h1>
<span class="label label-default">{{ location.latitude }}, {{ location.longitude }}</span>
<hr>
<div class="forecast-tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#qpf" data-toggle="tab">QPF</a></li>
        <li><a href="#nws" data-toggle="tab">NWS</a></li>
        <li><a href="#radar" data-toggle="tab">Radar</a></li>
        <li><a href="#forecastio" data-toggle="tab">Forecast.io</a></li>
        <li><a href="#wunderground" data-toggle="tab">Wunderground</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="qpf">
            <div class="tab-btn">
                <a href="{{ url_for('.update_location', id=location.id) }}" class="btn btn-primary {% if not location.is_outdated(hours=6) %}disabled{% endif %}">Update {% if location.is_outdated(hours=6) %}<span class="glyphicon glyphicon-refresh"></span>{% else %}(up to date){% endif %}</a>
                <div class="pull-right">
                    <a class="btn btn-default" href="http://www.hpc.ncep.noaa.gov/qpf/qpf2.shtml" target="_blank">External <span class="glyphicon glyphicon-new-window"></span></a>
                </div>
            </div>
            <table class="table table-striped">
                <thead>
                    <th>Product</th>
                    <th>Period</th>
                    <th>Duration</th>
                    <th>Valid Period (local tz)</th>
                    <th>Amount (in)</th>
                    <th>Updated</th>
                </thead>
                <tbody>
                    {% for forecast in location.latest_forecasts|sort(attribute='valid_start')|sort(attribute='valid_end') %}
                        <tr class={% if forecast.duration == 24 %}
                                "info"
                            {% elif forecast.duration == 48 %}
                                "warning"
                            {% elif forecast.duration > 48 %}
                                "danger"
                            {% else %}
                                ""
                            {% endif %}>
                            <td>{{ forecast.product }}</td>
                            <td>{{ forecast.period }}</td>
                            <td>{{ forecast.duration }}</td>
                            <td>{{ moment(forecast.valid_start).format('ddd h a') }} -
                                {{ moment(forecast.valid_end).format('ddd h a') }}</td>
                            <td>{{ AMOUNTS[forecast.value] }}</td>
                            <td>{{ moment(forecast.timestamp).fromTime(now) }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="nws">
            <div class="tab-btn pull-right">
                <a class="btn btn-default" href="{{ link_nws }}" target="_blank">External <span class="glyphicon glyphicon-new-window"></span></a>
            </div>
            <iframe src="{{ link_nws }}" frameborder="0" class="full-tab"></iframe>
        </div>
        <div class="tab-pane" id="radar">
            <div class="tab-btn pull-right">
                <a class="btn btn-default" href="{{ link_radar }}" target="_blank">External <span class="glyphicon glyphicon-new-window"></span></a>
            </div>
            <iframe src="{{ link_radar }}" frameborder="0" class="full-tab"></iframe>
        </div>
        <div class="tab-pane" id="forecastio">
            <div class="tab-btn pull-right">
                <a class="btn btn-default" href="{{ link_forecastio }}" target="_blank">External <span class="glyphicon glyphicon-new-window"></span></a>
            </div>
            <iframe id="forecast_embed" type="text/html" frameborder="0" height="245" width="100%" src="{{ link_forecastio_embed }}"> </iframe>
            <hr>
            <iframe src="{{ link_forecastio_lines }}" frameborder="0" class="full-tab"></iframe>
        </div>
        <div class="tab-pane" id="wunderground">
            <div class="tab-btn pull-right">
                <a class="btn btn-default" href="{{ link_wunderground }}" target="_blank">External <span class="glyphicon glyphicon-new-window"></span></a>
            </div>
            <iframe src="{{ link_wunderground }}" frameborder="0" class="full-tab"></iframe>
        </div>
    </div>
</div>
{% endblock %}

app/templates/location_list.html
{% extends "base.html" %}

{% block page_content %}
<h1>Locations</h1>
<ul class="locations">
    {% for location in locations|sort(attribute='name') %}
    <li class="location">
        <div class="title">
            <a href="{{ url_for('.location', id=location.id) }}">{{ location.name }}</a>
        </div>
        <div>
            <span class="label label-default">{{ location.latitude }}, {{ location.longitude }}</span>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}